steps:
  lint:
    image: rust
    commands:
      - cargo clippy
  build:
    image: rust
    commands:
      - echo "Building Step"
      - make build
  test:
    image: rust
    commands:
      - echo "Testing"
      - make test
