[package]
name = "ginst"
version = "v0.1.2"
edition = "2021"
description = "A generic installation tool, able to read and execute instructions from a json file."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
crossterm = "0.25.0"
json = "0.12.4"
tui = "0.19.0"
